[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  command = "apt-get update && apt-get install -y libmysqlclient-dev && pip install -r requirements.txt && npm run build"

[build.environment]
PYTHON_VERSION = "3.12.3"  # Use a stable Python version
MYSQLCLIENT_CFLAGS = "-I/usr/include/mysql"
MYSQLCLIENT_LDFLAGS = "-L/usr/lib/mysql -lmysqlclient"
