[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
PYTHON_VERSION = "3.13.1"
MYSQLCLIENT_CFLAGS = "-I/usr/include/mysql"
MYSQLCLIENT_LDFLAGS = "-L/usr/lib/mysql -lmysqlclient"

[build]
  base = "."
  publish = "build"
  command = "apt-get update && apt-get install -y libmysqlclient-dev && pip install -r requirements.txt && npm run build"